### ISSUE TITLE
Game Controller twitchiness at low power

### ISSUE THREAD

**Issue by samwinkelstein** [FRC8592/2021-Bot-Redo#12]
I noticed that the scale on the mariokart style drive for forward was:

```
//controlGame.java line 47
 this.forwardAxis = getdriveForce() / 0.70; //added a power mulltiplier

```
this might explain the twitchiness of the throttle.
dividing by .7 would result in a scale of getdriveForce()* 1.42.
please confirm if this the requested behavior if not, please fix it.

**Comment by EpsilonZolton** [comment]
fixed in the field no worrys
